export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATGORIES_START: 'category/FETCH_CATEGORIES_START',
    FETCH_CATGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATGORIES_FAILED: 'category/FETCH_CATEGORIES_FAILED',
  };
  
